- name: Install Apache on VM3
  hosts: apache_hosts
  gather_facts: no


  tasks:
    - name: Install Apache web server
      package:
        name: httpd  # Package name for Apache on CentOS
        state: present  # Ensure the package is present

    - name: Start Apache service and enable it on boot
      service:
        name: httpd  # Service name for Apache on CentOS
        state: started
        enabled: yes

    - name: Check if Apache service is enabled
      command: systemctl is-enabled httpd
      register: apache_enabled
      ignore_errors: true  # Ignore errors in case the service is not enabled

    - name: Print Apache service status
      debug:
        msg: "Apache service is {{ 'enabled' if apache_enabled.rc == 0 else 'not enabled' }}"
